- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
  - [mkdir -p ~/bin]
  - [mkdir -p ~/.config]

# zsh
- shell:
  - [mkdir -p ~/.zshlocal/pre]
  - [mkdir -p ~/.zshlocal/post]
  - [touch ~/.zshlocal/secrets]
  - [chmod 600 ~/.zshlocal/secrets]

- link:
    ~/.zshrc:
      path: zshrc
      force: yes
    ~/.zsh: zsh

# vim & nvim
- link:
    ~/.vim: vim
    ~/.config/nvim: vim

- link:
    ~/.vimrc: vimrc
    ~/.config/nvim/init.vim: vimrc

- shell:
    - ['{type -p vim && vim +PluginInstall +qall} || true']
    - ['{type -p nvim && nvim +PluginInstall +qall} || true']

# git
- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore.global: gitignore.global
    ~/.git-templates: git-templates
    ~/bin/git-review-pr: bin/git-review-pr
