# configuration for dotbot
---
- defaults:
    link:
      relink: true

- clean: ["~"]

- shell:
    - mkdir -p ~/bin
    - mkdir -p ~/.config

# zsh
- shell:
    - mkdir -p ~/.zinit

- link:
    ~/.zshrc:
      path: zshrc
      force: yes
    ~/.zsh: zsh
    ~/.zinit/bin: zinit

- shell:
    - mkdir -p ~/.zsh/.cache
    - mkdir -p ~/.zshlocal/pre
    - mkdir -p ~/.zshlocal/post

# vim
- shell:
    - mkdir -p ~/.vimtmp

- link:
    ~/.vim: vim

- link:
    ~/.vimrc: vimrc

- shell:
    - zsh -c '{type -p vim && vim +PluginInstall +qall} || true'

# git
- shell:
    - mkdir -p ~/.gnupg
    - chmod 0700 ~/.gnupg

- link:
    ~/.gitconfig: gitconfig
    ~/.gitconfig.prefer-ssh:
      if: "ssh git@github.com -o'StrictHostKeyChecking=accept-new' 2>&1 | grep -q 'successfully authenticated'"
      path: gitconfig.prefer-ssh
    ~/.gitignore.global: gitignore.global
    ~/bin/git-review-pr: bin/git-review-pr

# starship
- link:
    ~/.config/starship.toml: starship.toml

# mackup
- link:
    ~/.mackup.cfg:
      path: mackup.cfg
