# configuration for dotbot
---
- defaults:
    link:
      relink: true

- clean: ["~"]

- shell:
    - mkdir -p ~/bin
    - mkdir -p ~/.config

# zsh
- shell:
    - mkdir -p ~/.zshlocal/pre
    - mkdir -p ~/.zshlocal/post
    - mkdir -p ~/.zplugin
    - touch ~/.zshlocal/secrets
    - chmod 600 ~/.zshlocal/secrets

- link:
    ~/.zshrc:
      path: zshrc
      force: yes
    ~/.zsh: zsh
    ~/.zplugin/bin: zplugin

# vim
- shell:
    - mkdir -p ~/.vimtmp

- link:
    ~/.vim: vim

- link:
    ~/.vimrc: vimrc

- shell:
    - zsh -c '{type -p vim && vim +PluginInstall +qall} || true'

# git
- link:
    ~/.gitconfig: gitconfig
    ~/kiwi/gitconfig: kiwi/gitconfig
    ~/astro/gitconfig: astro/gitconfig
    ~/.gitignore.global: gitignore.global
    ~/bin/git-review-pr: bin/git-review-pr
