# configuration for dotbot
---
- defaults:
    link:
      relink: true

- clean: ["~"]

- shell:
    - mkdir -p ~/bin
    - mkdir -p ~/.config

# zsh
- shell:
    - mkdir -p ~/.zinit

- link:
    ~/.zshrc:
      path: zshrc
      force: yes
    ~/.zsh: zsh
    ~/.zinit/bin: zinit

- shell:
    - mkdir -p ~/.zsh/.cache

# vim
- shell:
    - mkdir -p ~/.vimtmp

- link:
    ~/.vim: vim

- link:
    ~/.vimrc: vimrc

- shell:
    - zsh -c '{type -p vim && vim +PluginInstall +qall} || true'

# git
- shell:
    - mkdir -p ~/.gnupg
    - chmod 0700 ~/.gnupg

- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore.global: gitignore.global
    ~/bin/git-review-pr: bin/git-review-pr
    ~/.gnupg/gpg.conf:
      if: "[ `uname` = Darwin ]"
      path: gnupg/gpg.conf
    ~/.gnupg/gpg-agent.conf:
      if: "[ `uname` = Darwin ]"
      path: gnupg/gpg-agent.conf

# starship
- link:
    ~/.config/starship.toml: starship.toml
