# configuration for dotbot
---
- defaults:
    link:
      relink: true

- clean: ["~"]

- shell:
    - mkdir -p ~/bin
    - mkdir -p ~/.config

# zsh
- shell:
    - mkdir -p ~/.zplugin

- link:
    ~/.zshrc:
      path: zshrc
      force: yes
    ~/.zsh: zsh
    ~/.zplugin/bin: zplugin

- shell:
    - mkdir -p ~/.zsh/.cache
    - mkdir -p ~/.zshlocal/pre
    - mkdir -p ~/.zshlocal/post
    - touch ~/.zshlocal/secrets
    - chmod 0700 ~/.zshlocal/secrets

# vim
- shell:
    - mkdir -p ~/.vimtmp

- link:
    ~/.vim: vim

- link:
    ~/.vimrc: vimrc

- shell:
    - zsh -c '{type -p vim && vim +PluginInstall +qall} || true'

# git
- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore.global: gitignore.global
    ~/bin/git-review-pr: bin/git-review-pr
    ~/.gnupg/gpg.conf:
      if: '[ `uname` = Darwin ]'
      path: gnupg/gpg.conf
    ~/.gnupg/gpg-agent.conf:
      if: '[ `uname` = Darwin ]'
      path: gnupg/gpg-agent.conf
